### ISSUE TITLE
Add Firebase Firestore To Store Orders

### ISSUE THREAD

**Issue by anuragrao04** [TheGrowPalProject/growpal#1]
## About

As for now, every order that has been placed just redirects you to the home page. It does not get logged anywhere. In simple words, there is no backend. Implement a firebase firestore that keeps a log of all orders placed on the website with necessary details. 

## Resources

This requires me to share the firebase API keys to you. When you work on this issue, approach me/ Reply to the issue to get the API keys.

**Comment by anuragrao04** [comment]
Firebase backend will also do!

**Comment by sujay1844** [comment]
Can I get assigned to this issue?

**Comment by anuragrao04** [comment]
@sujay1844 sure, go ahead

**Comment by ProSai45** [comment]
can you assign me this??

**Comment by anuragrao04** [comment]
@ProSai8055 this has been assigned to sujay and I cannot assign it to you unless he fails to solve the issue

**Comment by 411sst** [comment]
can i get assigned if this is still open?

**Comment by sujay1844** [comment]
@anuragrao04 I give up

**Comment by ProSai8055** [comment]
@anuragrao04 can you check with @sujay1844  its been more then 3 hours

**Comment by 411sst** [comment]
can i get assigned?? the issue hasnt been solved yet

**Comment by anuragrao04** [comment]
solved by @sujay1844
