### ISSUE TITLE
Convert to dark theme

### ISSUE THREAD

**Issue by anuragrao04** [TheGrowPalProject/growpal#14]
## About

The app now is completely in light theme. Implement a dark theme. This dark theme can either be a permanent dark theme or a switch to toggle between dark and light theme. This is up to you. The max block time and the bounty will vary accordingly

## Bounty 40 or 70

**Comment by laksh29** [comment]
Hey @anuragrao04 can I take this up ?

**Comment by anuragrao04** [comment]
Hey, I'm sorry but this issue is part of an internal hacktoberfest event

**Comment by NishanHolla** [comment]
can you allocate this problem to me

**Comment by anuragrao04** [comment]
@NishanHolla Sorry for the delay and please go ahead!

**Comment by RitwikAg120** [comment]
can u allocate to me

**Comment by anuragrao04** [comment]
@NishanHolla since there is no update from you, @Ritwik-Ag is being assigned.

**Comment by NishanHolla** [comment]
sorry i wasnt able to work on this as my flutter sdk had some error if @Ritwik-Ag isnt able to fix this pls give me another chance .

**Comment by anuragrao04** [comment]
@NishanHolla has the flutter SDK issue been solved?

**Comment by anuragrao04** [comment]
@NishanHolla you can go ahead. You have another 30 mins. Send in a comment if you have gone for dinner though. Concessions will be made in that case, obviously. Also, please don't make spam comments on every other repo. Maintainers have started to take notice.

**Comment by NishanHolla** [comment]
Sorry i didnt unassign myself from tasks after being assigned to other task. Can i be assigned later as i am going to dinner please.

**Comment by anuragrao04** [comment]
sure, have your dinner peacefully and resume working :D

**Comment by NishanHolla** [comment]
came back from dinner , working on the dark theme.

**Comment by 411sst** [comment]
can i get assigned if this is still open?

**Comment by NishanHolla** [comment]
i have submitted a PR

**Comment by NishanHolla** [comment]
Almost done just a few changes .

**Comment by anuragrao04** [comment]
all the best @NishanHolla

**Comment by NishanHolla** [comment]
I have finished all the changes and i hope you like the design @anuragrao04 .
