### ISSUE TITLE
Add Sound When Order Is Placed

### ISSUE THREAD

**Issue by anuragrao04** [TheGrowPalProject/growpal#4]
# Explanation
When an order is placed, after checkout, we need audio or vibrational feedback for the user. 

# Possibly Way To Implement
Use flutter packages to implement vibration and audio. 

# Resources
[Vibration Package](https://pub.dev/packages/vibration)
[Audio](https://bennett4.medium.com/adding-custom-sound-effects-to-a-flutter-mobile-app-41594f1f3305)

# Intial Time For Open Access: 30 Mins

# Maximum Allowed Block Time: 1Hr 30Mins

# Bounty Points: 70

**Comment by varuni7** [comment]
Can I work on this ?

**Comment by anuragrao04** [comment]
sure, go ahead!

**Comment by NandanHemanth** [comment]
Can i work on this?

**Comment by shrutidewan** [comment]
can I work on this?

**Comment by anuragrao04** [comment]
@varuni7 has made significant progress and is about to push. She has also added an extra feature!

**Comment by anuragrao04** [comment]
she's added tts!

**Comment by NandanHemanth** [comment]
Can i Work on this ISSUE nigel?
